language: objective-c
osx_image: xcode61
before_install:
    - brew update >/dev/null
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
xcode_workspace: Example/VOKUtilities.xcworkspace
xcode_scheme: VOKUtilities
xcode_sdk: iphonesimulator8.1
after_script:
    - pod lib lint --only-errors
