language: objective-c
osx_image: xcode8.2
env:
  global:
    - SCAN_WORKSPACE="Example/VOKUtilities.xcworkspace"
  matrix:
    # Define the details for each test suite that should be run
    - SCAN_SCHEME="VOKUtilities-Example" 
    - SCAN_SCHEME="VOKUtilities-tvOS"    SCAN_SDK="appletvsimulator"
    - SCAN_SCHEME="VOKUtilities-OSX"     SCAN_SDK="macosx"
script:
  - bundle exec fastlane scan
  - bundle exec pod lib lint
cache:
  - bundler  # After main-repo builds, save the "bundler" (local Ruby gems) stuff to cache for future builds.
